-- F1 2012 Track Recorder

local ffi = require('ffi')
local base = Memory.GetModuleBase('F1_2012.exe')

local function resolve(baseAddr, offsets)
    local addr = baseAddr + offsets[1]
    for i = 2, #offsets do
        addr = Memory.ReadMemory(addr, 4)
        if not addr or addr == 0 then
            return nil
        end
        addr = addr + offsets[i]
    end
    return addr
end

local carBase = resolve(base, {0x00DD5ABC, 0x50, 0x4A8, 0x38, 0x1A0})
local lapAddr = resolve(base, {0x00DD5A94, 0x78, 0xA18})

local recording = false
local data = {}
local lapStart = 0
local toggle = Keys.VK_F7

local function saveFiles()
    local dir = debug.getinfo(1, 'S').source:match('@(.+)[/\\]') .. '/'
    local f = io.open(dir .. 'ai_track.xml', 'w')
    f:write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
    f:write('<!--Generated by Track Recorder-->\n')
    f:write('<ai_track_data version_major="3" version_minor="0" version_revision="2">\n')
    f:write('  <track name="default">\n')
    f:write(string.format('    <gates num_gates="%d">\n', #data))
    for i, p in ipairs(data) do
        f:write(string.format('      <gate id="%d">\n', i - 1))
        f:write(string.format('        <position format="float3">%.2f %.2f %.2f</position>\n', p.x, p.y, p.z))
        f:write(string.format('        <normal format="float3">%.6f %.6f %.6f</normal>\n', p.fx, p.fy, p.fz))
        f:write('        <waypoints num_waypoints="1">\n')
        f:write('          <waypoint id="0" type="racing_line" length="0.0">\n')
        f:write('            <racing_line type="optimal" />\n')
        f:write('          </waypoint>\n')
        f:write('        </waypoints>\n')
        f:write('        <edges num_edges="0" />\n')
        f:write('      </gate>\n')
    end
    f:write('    </gates>\n')
    f:write('    <fork_sets num_fork_sets="0" />\n')
    f:write('  </track>\n')
    f:write('</ai_track_data>\n')
    f:close()

    f = io.open(dir .. 'ai_vehicle_track.xml', 'w')
    f:write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
    f:write('<!--Generated by Track Recorder-->\n')
    f:write('<vehicle_type_track_data version_major="3" version_minor="0" version_revision="0">\n')
    f:write('  <vehicle_track name="default">\n')
    f:write('    <vehicle_types />\n')
    f:write('  </vehicle_track>\n')
    f:write('</vehicle_type_track_data>\n')
    f:close()

    f = io.open(dir .. 'RacingLine.xml', 'w')
    f:write('<?xml version="1.0" encoding="UTF-8" ?>\n')
    f:write('<RacingLine>\n')
    f:write('  <Nodes>\n')
    for i, p in ipairs(data) do
        f:write(string.format('    <Node id="%d" x="%.2f" y="%.2f" z="%.2f" />\n', i - 1, p.x, p.y, p.z))
    end
    f:write('  </Nodes>\n')
    f:write('</RacingLine>\n')
    f:close()
end

local function readFloat(addr)
    return ffi.cast('float*', addr)[0]
end

function OnFrame()
    if not carBase or not lapAddr then
        SCRIPT_RESULT = 'Waiting for game...'
        carBase = resolve(base, {0x00DD5ABC, 0x50, 0x4A8, 0x38, 0x1A0})
        lapAddr = resolve(base, {0x00DD5A94, 0x78, 0xA18})
        return true
    end

    if Keyboard.IsKeyPressed(toggle) then
        if recording then
            saveFiles()
            data = {}
            recording = false
            SCRIPT_RESULT = 'Saved track'
        else
            lapStart = Memory.ReadMemory(lapAddr, 1) or 0
            data = {}
            recording = true
            SCRIPT_RESULT = 'Recording...'
        end
        return true
    end

    if not recording then
        return false
    end

    local x = readFloat(carBase)
    local y = readFloat(carBase + 4)
    local z = readFloat(carBase + 8)
    local fx = readFloat(carBase - 0x10)
    local fy = readFloat(carBase - 0x0C)
    local fz = readFloat(carBase - 0x08)

    table.insert(data, {x = x, y = y, z = z, fx = fx, fy = fy, fz = fz})

    local lap = Memory.ReadMemory(lapAddr, 1) or lapStart
    if lap ~= lapStart then
        recording = false
        saveFiles()
        data = {}
        SCRIPT_RESULT = 'Lap completed'
    end

    return true
end

SCRIPT_RESULT = 'Press F7 to record'

